name: plants_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  fluttertoast: ^8.2.5
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/